CREATE TABLE IF NOT EXISTS client (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    country VARCHAR(10) DEFAULT NULL,
    modules JSON DEFAULT NULL,
    notifications TINYINT(1) NOT NULL DEFAULT 0,
    iban VARCHAR(34) DEFAULT NULL,
    bic VARCHAR(11) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
