<?php
namespace Tests\Unit;
use App\Core\Exceptions\RedirectException;
use App\Providers\OfficeAccessTokenProvider;
use App\Services\AuthService;
use App\Services\Oidc\{OidcDiscoveryProvider, OidcHttpClientInterface, OidcIdentityException, OidcProtocolException, OidcSessionExpiredException, OidcSessionService, OidcTokenRefresher, OidcTransportException};
use PHPUnit\Framework\TestCase;
final class OidcSessionAndProviderTest extends TestCase
{
    protected function setUp():void{parent::setUp();if(session_status()===PHP_SESSION_ACTIVE)session_write_close();session_save_path(sys_get_temp_dir());session_name('oidc_session_test');session_start();$_SESSION=[];}
    protected function tearDown():void{$_SESSION=[];if(session_status()===PHP_SESSION_ACTIVE)session_write_close();parent::tearDown();}
    public function testSessionIdentityTokenExpiryAuthFacadeAndLogout():void{$s=new OidcSessionService();$c=(object)['sub'=>'user:123e4567-e89b-12d3-a456-426614174000','tenant_id'=>'123e4567-e89b-12d3-a456-426614174001'];$s->create($c,['sub'=>$c->sub,'tenant_id'=>$c->tenant_id,'given_name'=>'Ada','family_name'=>'Lovelace','email'=>'ada@example.test'],3600,['openid','read:clients']);$s->storeTokenSet('token','refresh',3600);$auth=new AuthService($s);$user=$auth->verify();self::assertSame($c->sub,$user->sub);self::assertSame($c->tenant_id,$user->tenant_uuid);self::assertSame('Ada',$user->firstname);self::assertArrayHasKey('initials',$_SESSION['office_identity']);self::assertSame('token',(new OfficeAccessTokenProvider($s,$this->createMock(OidcTokenRefresher::class)))->accessToken());$_SESSION['office_oauth']['expires_at']=time();self::assertFalse($s->isAuthenticated());try{$auth->verify(false);self::fail();}catch(RedirectException $e){self::assertStringStartsWith('/auth/oidc/login',$e->getLocation());}$s->logout();self::assertSame([],$_SESSION);}
    public function testProviderDoesNotConvertUnexpectedErrorsToRedirect():void{$mock=$this->createMock(OidcSessionService::class);$mock->method('accessToken')->willThrowException(new \RuntimeException('bug'));$this->expectException(\RuntimeException::class);(new OfficeAccessTokenProvider($mock,$this->createMock(OidcTokenRefresher::class)))->accessToken();}
    /** @dataProvider incoherentUserInfo */
    public function testIncoherentUserInfoIsClassifiedAsIdentityError(array $userinfo):void{$claims=(object)['sub'=>'user:123e4567-e89b-12d3-a456-426614174000','tenant_id'=>'123e4567-e89b-12d3-a456-426614174001'];$this->expectException(OidcIdentityException::class);(new OidcSessionService())->create($claims,$userinfo,3600,['openid']);}
    public static function incoherentUserInfo():array{return [[['sub'=>'user:123e4567-e89b-12d3-a456-426614174999','tenant_id'=>'123e4567-e89b-12d3-a456-426614174001']],[['sub'=>'user:123e4567-e89b-12d3-a456-426614174000','tenant_id'=>'123e4567-e89b-12d3-a456-426614174999']],[['sub'=>'user:123e4567-e89b-12d3-a456-426614174000','tenant_id'=>'not-a-uuid']]];}
    public function testValidAccessTokenDoesNotRefresh():void{$sessions=new OidcSessionService();$sessions->storeTokenSet('access','refresh',3600);$refresher=$this->createMock(OidcTokenRefresher::class);$refresher->expects(self::never())->method('refresh');self::assertSame('access',(new OfficeAccessTokenProvider($sessions,$refresher))->accessToken());}
    public function testRefreshRotatesTokensAndScopesWithoutSendingResource():void{$http=new RefreshFakeHttp(['status'=>200,'body'=>['access_token'=>'access-b','refresh_token'=>'refresh-b','token_type'=>'Bearer','expires_in'=>3600,'scope'=>'read:clients']]);$sessions=new OidcSessionService();$sessions->storeTokenSet('access-a','refresh-a',1);$_SESSION['office_identity']=['scopes'=>['openid','read:clients','write:clients']];$refresher=new OidcTokenRefresher($http,new OidcDiscoveryProvider($http,'https://login.devsys.fr',0),$sessions,'office-web','secret');self::assertSame('access-b',$refresher->refresh());self::assertSame(['grant_type'=>'refresh_token','refresh_token'=>'refresh-a'],$http->fields);self::assertSame(['office-web','secret'],$http->basicAuth);self::assertSame('refresh-b',$_SESSION['office_oauth']['refresh_token']);self::assertSame(['read:clients'],$_SESSION['office_identity']['scopes']);}
    public function testRefreshFailurePurgesSessionAndRedirectsWithoutRetry():void{$sessions=new OidcSessionService();$sessions->storeTokenSet('access','refresh',1);$refresher=$this->createMock(OidcTokenRefresher::class);$refresher->expects(self::once())->method('refresh')->willThrowException(new OidcProtocolException('invalid_grant'));$this->expectException(RedirectException::class);try{(new OfficeAccessTokenProvider($sessions,$refresher))->accessToken();}finally{self::assertSame([],$_SESSION);}}
    public function testNetworkRefreshFailureIsAttemptedOnlyOnce():void{$sessions=new OidcSessionService();$sessions->storeTokenSet('access','refresh',1);$http=new RefreshFakeHttp(null,new OidcTransportException('timeout'));$refresher=new OidcTokenRefresher($http,new OidcDiscoveryProvider($http,'https://login.devsys.fr',0),$sessions,'office-web','secret');$this->expectException(OidcTransportException::class);try{$refresher->refresh();}finally{self::assertSame(1,$http->calls);self::assertSame('refresh',$_SESSION['office_oauth']['refresh_token']);}}
}
final class RefreshFakeHttp implements OidcHttpClientInterface
{
    public array $fields=[]; public ?array $basicAuth=null; public int $calls=0;
    public function __construct(private readonly ?array $response=null, private readonly ?\Throwable $failure=null){}
    public function getJson(string $url,array $headers=[]):array{return ['status'=>200,'body'=>['issuer'=>'https://login.devsys.fr','authorization_endpoint'=>'https://login.devsys.fr/oauth/authorize','token_endpoint'=>'https://login.devsys.fr/oauth/token','userinfo_endpoint'=>'https://login.devsys.fr/userinfo','jwks_uri'=>'https://login.devsys.fr/jwks'],'headers'=>[]];}
    public function postForm(string $url,array $fields,?array $basicAuth=null):array{$this->calls++;$this->fields=$fields;$this->basicAuth=$basicAuth;if($this->failure!==null)throw $this->failure;return $this->response??['status'=>500,'body'=>[],'headers'=>[]];}
    public function getBearer(string $url,string $token):array{return ['status'=>200,'body'=>[],'headers'=>[]];}
}
